POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "email@email.com",
    "password": "password"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "ban@gmail.com",
    "password": "123456"
}

###
GET http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDUzNWRlZTIyNjMzMjEzYzAyZWY4M2IiLCJpYXQiOjE2MTYwNzc3MDAsImV4cCI6MTYxNjE2NDEwMH0.f2UWb2POMZB69jGiNPBvZFvl0cmnR06nYobs3G2PvmA

###
PUT http://localhost:3000/api/sauces/6049fbfc480a3a170cc061cf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDUzNWRlZTIyNjMzMjEzYzAyZWY4M2IiLCJpYXQiOjE2MTYwNzc3MDAsImV4cCI6MTYxNjE2NDEwMH0.f2UWb2POMZB69jGiNPBvZFvl0cmnR06nYobs3G2PvmA
Content-Type: application/json

{
    "heat": "9"
}

